[clean-job-do-not-use] support get distinct job lasted and clean jobs
primedata-ai/kala pull request #1
Opened 2022-06-03 06:53 UTC by truongnguyen101195

2022-06-03 08:08 UTC, khanhngobackend requested changes
Almost all LGTM, except 1 (commented).

2022-06-03 08:08 UTC, khanhngobackend commented on job/cache.go
> +	go c.cronClearJobDoNotUse()
Why put this here instead of below the line `247` below to completely eliminate the possibility of race?

2022-06-03 09:05 UTC, huylenq commented
Discussed offline with @truongnguyen101195 , @khanhngobackend , @vyduong1207. @truongnguyen101195 will take a more thorough look at how these work.

2022-06-22 07:06 UTC, huylenq approved these changes
The concern of accidentally removing/filtering the latest version of the job record (instead of the stale version) is a stale one.
However, the jobs data in this service only serve execution purposes, not be referenced for bookkeeping/management sake, so losing records is actually not a big deal. So we can merge this, but please be aware if any issue related to job history surfaces.
@truongnguyen101195, @vyduong120, @khanhngobackend

2022-06-22 07:06 UTC, huylenq commented on .github/workflows/golangci-lint.yml
> -      - master
Shouldn't if there's no particular reason.

2022-06-22 07:06 UTC, huylenq commented on job/storage/postgres/postgres.go
> +select  coalesce(json_agg(j.job), '[]'::json) from %s j where ctid in (select ctid from clean where num = 1);`, TableName, TableName)
A quite surprising behavior, and may yield subtle bugs: "GetAll" does not actually returning "all", but only a subset from this filter. How about return deduplicated result but regardless of the job's completion status to reserve the current semantic?
```suggestion
	query := fmt.Sprintf(
		`with incomplete_jobs as (
			select ctid,
					row_number() over(partition by (job->'id') order by (job->'metadata'->'last_attempted_run') desc) as row_num 
				from %s) 
		select coalesce(json_agg(j.job), '[]'::json)
		from %s j
		where ctid in (select ctid from incomplete_jobs where row_num = 1);`,
		TableName, TableName)
```

2023-02-07 04:27 UTC, merged